### ISSUE TITLE
TECH: Setup Bootstrap and Crispy Forms

### ISSUE THREAD

**Issue by pavlo-myskov** [FlashDrag/cyclebay#11]
### Tasks:

- [x] - Add and configure base template
- [x] - Add bootstrap cdn to base template
- [x] - Install django-crispy-forms: `pip install django-crispy-forms`
- [x] - Add `crispy_forms` to the INSTALLED_APPS in settings.py
- [x] - Install Bootstrap4 template pack for django-crispy-forms: `pip install crispy-bootstrap4`
- [x] - Add CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5" and CRISPY_TEMPLATE_PACK = "bootstrap4" to settings.py
- [x] - To use the Bootstrap template pack, add the `{% load crispy_forms_tags %}` to the `base.html` file of the project
