### ISSUE TITLE
TECH: Configure AWS S3 for static and media files

### ISSUE THREAD

**Issue by FlashDrag** [FlashDrag/cyclebay#6]
### Tasks:

- [x] - Configure a new bucket in AWS S3
- [x] - Connect Django to S3
- [x] - Upload static and media files
